import React from "react";
import { Link } from "react-router-dom";
import { ShieldCheck, Lock, Bot } from "lucide-react";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import StackAnimation from "../components/StackAnimation";

export default function Landing() {
  return (
    <div className="min-h-screen flex flex-col bg-forti-black text-forti-cyan">
      <Navbar />

      <section className="text-center pt-16 px-6 flex-1">
        <h1 className="text-4xl md:text-6xl font-black tracking-wider mb-4">
          FORTI<span className="text-white">TRADE</span> AI
        </h1>
        <p className="text-forti-cyan/70 max-w-xl mx-auto text-sm md:text-base">
          A fraud-aware trading bot that scans every trade for risk before it executes —
          powered by real-time detection and Gemma AI reasoning.
        </p>
        <div className="flex justify-center gap-4 mt-8">
          <Link
            to="/login"
            className="bg-forti-cyan text-forti-black font-bold tracking-widest text-sm px-6 py-3 rounded-md hover:shadow-glow transition"
          >
            LAUNCH APP
          </Link>
        </div>
      </section>

      <StackAnimation />

      <section className="grid md:grid-cols-3 gap-6 max-w-5xl mx-auto px-6 pb-20">
        <FeatureCard
          icon={<ShieldCheck size={28} />}
          title="Fraud Detection"
          desc="Every trade is scored against rapid-fire, volume, device, and location risk factors before execution."
        />
        <FeatureCard
          icon={<Bot size={28} />}
          title="Gemma AI Reasoning"
          desc="Flagged trades get a plain-language risk explanation generated by Gemma via Fireworks AI."
        />
        <FeatureCard
          icon={<Lock size={28} />}
          title="Secured Execution"
          desc="High-risk trades are auto-blocked pending review, protecting your account from takeover patterns."
        />
      </section>

      <Footer />
    </div>
  );
}

function FeatureCard({ icon, title, desc }) {
  return (
    <div className="bg-forti-panel border border-forti-cyan-dim/40 rounded-xl p-6 hover:border-forti-cyan/50 transition">
      <div className="text-forti-cyan mb-3">{icon}</div>
      <h3 className="font-bold tracking-wide mb-2 text-sm uppercase">{title}</h3>
      <p className="text-forti-cyan/60 text-sm">{desc}</p>
    </div>
  );
}